apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp  # Matches both canary and stable
  ports:
  - port: 80
    targetPort: 80
  type: NodePort  # or ClusterIP/LoadBalancer depending on your setup
