apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blue-service
  labels:
    app: app-blue
    version: blue 
spec:
  replicas: 10
  selector:
    matchLabels: 
      app: app-blue
      version: blue
  template: 
    metadata:
     labels: 
      app: blue
      version: blue
    spec: 
      containers: 
      - name: blue-service
        image: nginx:1.14.1
        ports:
        - containerPort: 80              
