apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blue-service
  labels:
    app: blue
spec:
  replicas: 10
  selector:
    matchLabel: 
      app: blue
  template: 
    metadata:
     labe        
