apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: green  # Change this to 'green' during deployment switch
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
